name: Build and publish NuGet

on:
  push:
    branches: [ master, ci-update ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.1.x
          5.0.x
          6.0.x
          8.0.x
    - name: Build
      run: dotnet build --configuration Release
    - name: Pack
      run: dotnet pack src/SpatialFocus.EntityFrameworkCore.Extensions.csproj --output . --configuration Release
    - name: Push
      run: dotnet nuget push *.nupkg --skip-duplicate --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
